# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab922aa0ce1d0e9f2fddecefc6c5499aee6f95054f0487b892cb201e637a66b8bc14a4db7aed7dc798c77dbfc37f08a993db8f7ae45b72f01e3837462d44ae2b

test:
  secret_key_base: fc2a6e664f08b07e4c7e1a23f11e0c712c01226c3f4089c5b80024de17cd2d079e8d92806f412412f22adb1630f9b62eec38c3b6f5fe994ad4f03d1bb8be9bd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
